#!/bin/bash

killServers() {
    echo "Killing servers"
    pkill biologistd
    pkill -f SimpleHTTPServer
}

trap "killServers" SIGINT SIGKILL SIGTERM

[ $# -gt 0 -a "$1" == "--kill" ] && {
    killServers
    exit 0
}

echo "[Starting httpd server]"

pkill -f SimpleHTTPServer

[ $# -gt 0 ] && httpdPort=$1 || httpdPort=8080
python2 -m SimpleHTTPServer ${httpdPort} &

echo "[Starting biologistd server]"

pkill biologistd

# [ $# -gt 0 ] && biologistdPort=$1 || biologistdPort=8080

biologistd --port 8081
